swagger: '2.0'
info:
  description: Swagger - Phase 2 - Transaction
  version: 1.0.0
  title: 'ArgentBank : API documentation for transaction'
  termsOfService: http://swagger.io/terms/
host: localhost:3001
basePath: /api/v1
schemes:
  - https
  - http
paths:
  /transaction/{userId}/{month}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions for current month
      summary: View all user's transactions for the current month;
      description: >-
        API for fetching the transactions in the current month for a specific
        user
      operationId: readAllTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: userId
          required: true
          type: integer
          description: a specific user's id
        - in: path
          name: month
          required: true
          type: string
          description: current month
      responses:
        '200':
          description: Successfully get user's all transactions for the current month
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  
  /transaction/operation/{userId}/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - CRUD with transactions
      summary: View the details of a specific transaction in another view
      description: API for fetching a transaction in detail of a specific user
      operationId: readUniqueTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: userId
          required: true
          type: integer
          description: a specific user's id
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction unique id
      responses:
        '200':
          description: Successfully get an user's specific transaction!
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - CRUD with transactions
      summary: Add a transaction information
      description: API for adding a new transaction information
      operationId: createTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: userId
          required: true
          type: integer
          description: a specific user's id
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction unique id
        - in: body
          name: body
          description: Created transaction object 
          required: true
          schema:
               $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Successfully created a transaction!
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - CRUD with transactions
      summary: Edit a specific transaction information
      description: API for updating an existent transaction
      operationId: updateTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: userId
          required: true
          type: integer
          description: a specific user's id
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction unique id
        - in: body
          name: body
          description: Updated transaction object 
          required: true
          schema:
               $ref: '#/definitions/Transaction'
      responses:
        '200':
          description: Successfully updated an user's specific transaction!
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - CRUD with transactions
      summary: Deletes a specific transaction information
      description: API for deleting an existent transaction
      operationId: deleteTransaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: userId
          required: true
          type: integer
          description: a specific user's id
        - in: path
          name: transactionId
          required: true
          type: integer
          description: Transaction unique id
      responses:
        '200':
          description: Successfully delete an existent transaction!
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  Transaction:
    type: object
    properties:
      status:
        type: integer
        example: 200
      message:
        type: string
        example: Success!
      transactions:
        type: object
        properties:
          id:
            type: string
            format: int64
            description: User id
            example: 20
          date:
            type: string
            format: date-time
            example: 2022-02-16T09:12:32.766Z
          description:
            type: string
            example: Argent Bank notification
          amount:
            type: integer
            example: 200
          balance:
            type: integer
            example: 5000
          type:
            type: string
            example: Electricity
          category:
            type: string
            example: Household
          notes:
            type: string
            example: Electricity bill for July 2022
